server:
  port: 8002

grpc:
 client:
  user-service:
   address: static://localhost:6565
   negotiationType: PLAINTEXT
  stock-service:
   address: static://localhost:6566
   negotiationType: PLAINTEXT