server:
  port: 8002

grpc:
 client:
  user-service:
   address: static://localhost:6565
   negotiationType: PLAINTEXT
#  other-service:
#   address: static://localhost:7575
#   negotiationType: PLAINTEXT